In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [ ]:
Challenge 1 – Complete Data Cleaning
Your manager gives you a messy dataset.
Perform all of the following:
• Load the dataset.
• Display dataset information.
• Find missing values.
• Remove duplicate rows.
• Fill missing values:
o Age → median
o Balance → mean
• Rename:
o Target → CustomerStatus
o AnnualIncome → Income
• Display the first 15 rows.

In [7]:
df.info()
df.isnull().sum()
df.drop_duplicates()
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Balance"]=df["Balance"].fillna(df["Balance"].mean())
df.rename(columns = {"Target" : "CustomerStatus", "AnnualIncome" : "Income"},inplace=True)
df.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

,CustomerID,Age,Income,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,CustomerStatus
0,10001,58.0,49184.0,2139,581,97523.535666,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.540000,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.920000,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.880000,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.460000,5,UK,Other,Corporate,Churn
5,10006,69.0,31390.0,48323,770,107245.620000,6,India,Other,Corporate,Stay
6,10007,58.0,182141.0,24200,891,38457.720000,1,India,Other,Retail,Churn
7,10008,67.0,95861.0,5729,538,173296.730000,6,UK,Female,SME,Stay
8,10009,41.0,62638.0,24760,663,41901.410000,4,France,Other,SME,Stay
9,10010,22.0,179680.0,42113,475,106827.980000,3,USA,Female,Corporate,Churn
10,10011,44.0,187772.0,45599,870,43923.030000,5,India,NaN,Retail,Stay
11,10012,69.0,102694.0,26790,574,13237.720000,9,France,Female,Retail,Churn
12,10013,59.0,150870.0,26428,769,28574.320000,2,USA,Other,SME,Stay
13,10014,52.0,88876.0,49456,898,85686.770000,9,Canada,Female,Retail,Stay
14,10015,26.0,153569.0,32843,393,151156.430000,1,USA,Other,Retail,Churn

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [ ]:
Challenge 2 – Banking Report
The bank wants a numeric report.
Tasks
• Select only numeric columns.
• Display summary statistics.
• Convert Age and CreditScore to float.
• Display information again.

In [5]:

numeric_df = df.select_dtypes(include=["number"])
numeric_df
df.describe()
numeric_df.describe()
df["Age"]=df["Age"].astype(float)
df["CreditScore"] = df["CreditScore"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   float64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(4), int64(3), object(4)
memory usage: 87.8+ KB

In [ ]:
Challenge 3 – Duplicate Investigation
Find duplicate customers.
Then
• Count duplicate rows.
• Remove duplicates.
• Print information before and after removing duplicates.
• Show the last 20 rows.

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [2]:
df.duplicated().sum()
df.info()
df.drop_duplicates(inplace=True)
df.info()
df.tail(20)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           950 non-null    float64
 2   AnnualIncome  950 non-null    float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       950 non-null    float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Target        1000 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
980,10981,41.0,199633.0,8498,847,173390.59,7,Canada,Male,Corporate,Stay
981,10982,34.0,98876.0,6414,541,59484.58,2,Canada,Other,Corporate,Stay
982,10983,69.0,188933.0,27126,334,NaN,1,Canada,Female,SME,Churn
983,10984,44.0,107221.0,47514,732,175352.25,1,USA,Other,Corporate,Churn
984,10985,50.0,37397.0,23559,730,120423.19,8,France,Female,Corporate,Stay
985,10986,62.0,27169.0,3914,488,126031.27,10,USA,Male,Corporate,Churn
986,10987,30.0,184704.0,20524,621,115161.87,1,USA,Male,SME,Churn
987,10988,63.0,190178.0,9025,720,158528.46,5,NaN,Female,SME,Stay
988,10989,26.0,88335.0,11869,635,159905.73,3,India,Female,Corporate,Stay
989,10990,29.0,123152.0,25228,884,44897.43,0,Germany,Other,SME,Churn
990,10991,58.0,79954.0,6331,773,39653.24,2,India,Female,SME,Stay
991,10992,45.0,NaN,17549,452,17812.25,5,USA,Other,Retail,Churn
992,10993,18.0,157845.0,29018,764,165451.49,7,India,Male,SME,Stay
993,10994,31.0,69950.0,17945,594,149288.61,6,USA,Female,Retail,Stay
994,10995,56.0,76509.0,19044,493,83666.20,6,USA,Male,Corporate,Churn
995,10996,34.0,81731.0,40980,761,181465.65,5,Germany,Other,SME,Stay
996,10997,47.0,42475.0,1176,780,26640.99,5,France,Female,SME,Stay
997,10998,31.0,120531.0,46929,733,147220.82,4,India,Male,SME,Stay
998,10999,21.0,33661.0,22314,540,94186.48,5,NaN,Other,SME,Stay
999,11000,63.0,31930.0,851,559,100908.40,6,UK,Female,NaN,Stay

In [ ]:
Challenge 4 – HR Department
HR wants better column names.
Rename
CustomerID → Employee_ID
Age → EmployeeAge
Gender → EmployeeGender
AnnualIncome → Salary
Target → PromotionStatus
Then
• Add prefix
HR_
to every column.
Display 10 random records.

In [2]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [3]:
df.rename(columns = {"CustomerID" : "Employee_ID", "Age" : "EmployeeAge","Gender":"EmployeeGender","AnnualIncome":" Salary","Target":"PromotionStatus"},inplace=True)
df = df.add_prefix("HR_")
print(df.sample(10))

     HR_Employee_ID  HR_EmployeeAge  HR_ Salary  HR_Spending  HR_CreditScore  \
134           10135            58.0     86578.0        30618             561
862           10863            60.0     31302.0         4040             672
765           10766            69.0    181299.0        27673             723
673           10674            67.0     85263.0        25718             753
454           10455            28.0    186772.0         6314             643
956           10957            47.0    192429.0        28187             881
510           10511            32.0     78804.0        48155             434
555           10556            53.0     34103.0         1349             557
671           10672            68.0     28319.0        22143             382
987           10988            63.0    190178.0         9025             720

     HR_Balance  HR_Tenure HR_Geography HR_EmployeeGender HR_Segment  \
134   133368.14          7           UK             Other        SME
862    57012.90          6           UK            Female        SME
765     9098.44          5      Germany             Other     Retail
673    49432.44          0          USA            Female        SME
454    89325.99          4          USA              Male        SME
956         NaN          6           UK              Male        SME
510         NaN          0          NaN               NaN     Retail
555    40617.44          7          USA             Other        SME
671   168709.26          2        India            Female  Corporate
987   158528.46          5          NaN            Female        SME

    HR_PromotionStatus
134               Stay
862               Stay
765              Churn
673              Churn
454               Stay
956               Stay
510              Churn
555               Stay
671              Churn
987               Stay

In [ ]:
Challenge 5 – Finance Cleaning
Finance department reports missing values.
Tasks
Fill
AnnualIncome → Median
Balance → Mean
Age → Median
Then
Generate descriptive statistics.

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [3]:
df["AnnualIncome"]=df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"]=df["Balance"].fillna(df["Balance"].mean())
df["Age"]=df["Age"].fillna(df["Age"].median())
print(df.describe())

         CustomerID          Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  1020.000000    1020.000000   1020.000000  1020.000000
mean   10501.599020    44.237255  112498.242157  25232.615686   602.659804
std      288.022115    15.136428   50925.015723  14219.393105   176.560690
min    10001.000000    18.000000   20227.000000    537.000000   300.000000
25%    10252.750000    31.000000   69223.000000  13134.750000   440.750000
50%    10502.500000    44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000    57.000000  155570.750000  37956.000000   757.250000
max    11000.000000    70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count    1020.000000  1020.000000
mean    97523.535666     5.261765
std     54382.357541     3.185330
min       547.600000     0.000000
25%     52145.757500     2.000000
50%     97523.535666     5.000000
75%    142086.700000     8.000000
max    199885.880000    10.000000

In [ ]:
Challenge 6 – Data Type Audit
The company says
Age and AnnualIncome are stored incorrectly.
Tasks
Convert
Age → int
AnnualIncome → float
Balance → float
Target → string
Print information.

In [4]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [ ]:
df['Age']=df['Age'].astype(int)
df['Balance']=df['Balance'].astype(float)
df['AnnualIncome']=df['AnnualIncome'].astype(float)
df['Target']=df['Target'].astype(str)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [ ]:
Challenge 7 – Customer Analytics
Create a new DataFrame that
• removes Segment
• removes Geography
• removes duplicate rows
Display
• first 10 rows
• dataset information
• statistical summary

In [9]:
df_new = df.drop(columns=["Segment", "Geography"])
df_new.drop_duplicates()
df_new.head(10)
df_new.info()
df_new.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           970 non-null    float64
 2   AnnualIncome  967 non-null    float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       969 non-null    float64
 6   Tenure        1020 non-null   int64
 7   Gender        968 non-null    object
 8   Target        1020 non-null   object
dtypes: float64(3), int64(4), object(2)
memory usage: 71.8+ KB

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1020.000000,970.000000,967.000000,1020.000000,1020.000000,969.000000,1020.000000
mean,10501.599020,44.249485,112505.928645,25232.615686,602.659804,97523.535666,5.261765
std,288.022115,15.521935,52303.362541,14219.393105,176.560690,55796.562543,3.185330
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10252.750000,30.250000,66149.000000,13134.750000,440.750000,50077.860000,2.000000
50%,10502.500000,44.000000,112358.000000,24798.000000,607.000000,95100.060000,5.000000
75%,10752.250000,58.000000,158000.500000,37956.000000,757.250000,143947.810000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [ ]:
Challenge 8 – ML Dataset Preparation
Prepare a machine learning dataset.
Perform
• Remove duplicates
• Remove CustomerID
• Remove Segment
• Fill missing values
• Rename Target to Output
Finally
Display
head()
info()
describe()
value_counts(Output)

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [2]:
df.drop_duplicates()
df.drop(columns=["Segment", "CustomerID"])
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.rename(columns={"Target":"Output"},inplace = True
df.head()
df.info()
df.describe()
df["Output"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Output        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Output
Churn    515
Stay     505
Name: count, dtype: int64

In [ ]:
Challenge 9 – Column Transformation
Create these new columns
NetWorth = Balance + AnnualIncome
AgeAfterRetirement = Age + 20
DoubleCreditScore = CreditScore * 2
IncomePerMonth = AnnualIncome / 12
Then
Display first 15 rows.

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [5]:
df["NetWorth"] = df["Balance"] + df["AnnualIncome"]
df["AgeAfterRetirement"] = df["Age"] + 20
df["DoubleCreditScore"] = df["CreditScore"] * 2
df["IncomePerMonth"] = df["AnnualIncome"] / 12
df.head(15)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,NetWorth,AgeAfterRetirement,DoubleCreditScore,IncomePerMonth
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,NaN,78.0,1162,4098.666667
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,169320.54,85.0,1464,13580.333333
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,170159.92,76.0,1006,2246.333333
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,232553.88,75.0,926,7743.833333
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,184221.46,86.0,788,9019.666667
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,138635.62,89.0,1540,2615.833333
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,220598.72,78.0,1782,15178.416667
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,269157.73,87.0,1076,7988.416667
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,104539.41,61.0,1326,5219.833333
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,286507.98,42.0,950,14973.333333
10,10011,NaN,187772.0,45599,870,43923.03,5,India,NaN,Retail,Stay,231695.03,NaN,1740,15647.666667
11,10012,69.0,102694.0,26790,574,13237.72,9,France,Female,Retail,Churn,115931.72,89.0,1148,8557.833333
12,10013,59.0,150870.0,26428,769,28574.32,2,USA,Other,SME,Stay,179444.32,79.0,1538,12572.500000
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay,174562.77,72.0,1796,7406.333333
14,10015,26.0,153569.0,32843,393,151156.43,1,USA,Other,Retail,Churn,304725.43,46.0,786,12797.416667

In [ ]:
Challenge 10 – Company Report
Display
• first five rows
• last five rows
• ten random rows
• dataset information
• descriptive statistics
Finally rename
Target → Customer_Status

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [8]:
df.head(5)
df.tail(5)
df.sample(10)
df.info()
df.describe()
df.rename(columns={"Target":"Customer_Status"},inplace=True)
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       1020 non-null   int64
 1   Age              970 non-null    float64
 2   AnnualIncome     967 non-null    float64
 3   Spending         1020 non-null   int64
 4   CreditScore      1020 non-null   int64
 5   Balance          969 non-null    float64
 6   Tenure           1020 non-null   int64
 7   Geography        969 non-null    object
 8   Gender           968 non-null    object
 9   Segment          969 non-null    object
 10  Customer_Status  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure', 'Geography', 'Gender', 'Segment',
       'Customer_Status'],
      dtype='object')

In [ ]:
Challenge 11 – Missing Value Report
Create a report showing
• Total missing values
• Numerical columns
• Mean of Balance
• Median of Age
• Fill missing values
• Display information again

In [9]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [11]:
print(df.isnull().sum())
print(df.select_dtypes(include="number").columns)
print(df["Balance"].mean())
print(df["Age"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df.info()

CustomerID       0
Age             50
AnnualIncome    53
Spending         0
CreditScore      0
Balance         51
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64
Index(['CustomerID', 'Age', 'AnnualIncome', 'Spending', 'CreditScore',
       'Balance', 'Tenure'],
      dtype='object')
97523.53566563467
44.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1020 non-null   int64
 1   Age           1020 non-null   float64
 2   AnnualIncome  1020 non-null   float64
 3   Spending      1020 non-null   int64
 4   CreditScore   1020 non-null   int64
 5   Balance       1020 non-null   float64
 6   Tenure        1020 non-null   int64
 7   Geography     969 non-null    object
 8   Gender        968 non-null    object
 9   Segment       969 non-null    object
 10  Target        1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [ ]:
Challenge 12 – Customer Classification
Count
Stay
Churn
Then
Rename
Target → Customer_Class
Convert it into string.

In [2]:
print(df["Target"].value_counts())
df.rename(columns={"Target": "Customer_Class"}, inplace=True)
df["Customer_Class"] = df["Customer_Class"].astype(str)
print(df.info())
print(df["Customer_Class"].value_counts())

Target
Churn    515
Stay     505
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   CustomerID      1020 non-null   int64
 1   Age             970 non-null    float64
 2   AnnualIncome    967 non-null    float64
 3   Spending        1020 non-null   int64
 4   CreditScore     1020 non-null   int64
 5   Balance         969 non-null    float64
 6   Tenure          1020 non-null   int64
 7   Geography       969 non-null    object
 8   Gender          968 non-null    object
 9   Segment         969 non-null    object
 10  Customer_Class  1020 non-null   object
dtypes: float64(3), int64(4), object(4)
memory usage: 87.8+ KB
None
Customer_Class
Churn    515
Stay     505
Name: count, dtype: int64

In [ ]:
Challenge 13 – Sales Department
Rename
Balance → AccountBalance
AnnualIncome → Salary
CreditScore → Score
Add prefix
Sales_
Then
Display
sample(20)

In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [4]:
df.rename(columns={"Balance": "AccountBalance"}, inplace=True)
df.rename(columns={"AnnualIncome": "Salary"}, inplace=True)
df.rename(columns={"CreditScore": "Score"}, inplace=True)
df.add_prefix("Sales_")
df.sample(20)

,CustomerID,Age,Salary,Spending,Score,AccountBalance,Tenure,Geography,Gender,Segment,Target
957,10958,48.0,174137.0,1957,624,75547.52,6,UK,Other,Retail,Stay
296,10297,36.0,127182.0,12295,438,153165.54,10,Canada,Female,Corporate,Churn
470,10471,69.0,169811.0,44902,450,24056.37,7,USA,Male,Retail,Churn
1014,10181,50.0,166466.0,44281,662,14415.10,0,Canada,Male,Corporate,Churn
62,10063,23.0,81569.0,44592,617,44928.13,3,USA,Male,Retail,Stay
13,10014,52.0,88876.0,49456,898,85686.77,9,Canada,Female,Retail,Stay
453,10454,58.0,NaN,7322,808,28128.67,1,USA,Female,NaN,Churn
661,10662,46.0,100705.0,24471,722,51961.41,4,India,Male,SME,Stay
791,10792,47.0,64774.0,18998,656,120888.05,2,Germany,Male,Corporate,Stay
694,10695,51.0,45459.0,7133,536,106332.21,3,USA,Other,SME,Stay
797,10798,22.0,176830.0,7626,688,65481.65,10,France,Male,Retail,Stay
268,10269,51.0,118782.0,21062,477,91932.71,8,UK,Other,Corporate,Churn
827,10828,43.0,140876.0,44755,547,146862.69,9,USA,Other,Corporate,Stay
53,10054,43.0,198131.0,35641,639,187847.43,1,UK,Male,SME,Churn
855,10856,57.0,118600.0,10838,316,175925.39,1,India,Male,NaN,Churn
688,10689,44.0,188009.0,21604,413,19251.26,10,India,Male,Retail,Churn
134,10135,58.0,86578.0,30618,561,133368.14,7,UK,Other,SME,Stay
896,10897,46.0,88264.0,24726,488,41031.07,0,France,Female,Corporate,Churn
49,10050,19.0,67018.0,48771,640,156477.30,6,France,Other,Retail,Stay
81,10082,31.0,141905.0,46340,562,153379.62,2,Germany,NaN,SME,Stay

In [ ]:
Challenge 14 – Interview Challenge
Without creating another DataFrame,
perform
• remove duplicates
• rename Target
• fill missing values
• convert Balance to float
• display summary

In [5]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [6]:
df.drop_duplicates(inplace=True)
df.rename(columns={"Target": "Output"}, inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Balance"] = df["Balance"].astype(float)
df.describe()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,10500.500000,44.202000,112452.763000,25285.558000,603.088000,97557.565779,5.241000
std,288.819436,15.130834,51081.480963,14211.735656,176.605486,54430.062006,3.179155
min,10001.000000,18.000000,20227.000000,537.000000,300.000000,547.600000,0.000000
25%,10250.750000,31.000000,68437.250000,13213.000000,441.000000,52074.240000,2.000000
50%,10500.500000,44.000000,112347.500000,24901.000000,606.500000,97557.565779,5.000000
75%,10750.250000,57.000000,155570.750000,37960.250000,758.250000,142297.910000,8.000000
max,11000.000000,70.000000,199967.000000,49995.000000,900.000000,199885.880000,10.000000

In [ ]:
Challenge 15 – Data Engineer Task
Load the dataset.
Create another DataFrame containing only numeric columns.
Drop
CustomerID
Target
Display summary.

In [1]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [4]:
new_df = df.select_dtypes(include="number")
print(new_df.describe())
new_df.drop(columns=["CustomerID", "Target"], inplace=True, errors="ignore")

         CustomerID         Age   AnnualIncome      Spending  CreditScore  \
count   1020.000000  970.000000     967.000000   1020.000000  1020.000000
mean   10501.599020   44.249485  112505.928645  25232.615686   602.659804
std      288.022115   15.521935   52303.362541  14219.393105   176.560690
min    10001.000000   18.000000   20227.000000    537.000000   300.000000
25%    10252.750000   30.250000   66149.000000  13134.750000   440.750000
50%    10502.500000   44.000000  112358.000000  24798.000000   607.000000
75%    10752.250000   58.000000  158000.500000  37956.000000   757.250000
max    11000.000000   70.000000  199967.000000  49995.000000   900.000000

             Balance       Tenure
count     969.000000  1020.000000
mean    97523.535666     5.261765
std     55796.562543     3.185330
min       547.600000     0.000000
25%     50077.860000     2.000000
50%     95100.060000     5.000000
75%    143947.810000     8.000000
max    199885.880000    10.000000

In [ ]:
Challenge 16 – Mixed Cleaning
Perform
drop_duplicates()
fillna()
astype()
rename()
head()
info()
using only one DataFrame variable.

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [7]:
df.drop_duplicates(inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df["Age"] = df["Age"].astype(int)
df["AnnualIncome"] = df["AnnualIncome"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df.rename(columns={"Target": "Output"}, inplace=True)
print(df.head())
df.info()

   CustomerID  Age  AnnualIncome  Spending  CreditScore        Balance  \
0       10001   58       49184.0      2139          581   97557.565779
1       10002   65      162964.0      6197          732    6356.540000
2       10003   56       26956.0     37281          503  143203.920000
3       10004   55       92926.0       925          463  139627.880000
4       10005   66      108236.0      7198          394   75985.460000

   Tenure Geography Gender    Segment Output
0       2    France   Male        SME   Stay
1       1       USA   Male        SME  Churn
2       8    Canada   Male  Corporate   Stay
3       5       NaN   Male     Retail  Churn
4       5        UK  Other  Corporate  Churn
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    1000 non-null   int64
 1   Age           1000 non-null   int64
 2   AnnualIncome  1000 non-null   float64
 3   Spending      1000 non-null   int64
 4   CreditScore   1000 non-null   int64
 5   Balance       1000 non-null   float64
 6   Tenure        1000 non-null   int64
 7   Geography     950 non-null    object
 8   Gender        950 non-null    object
 9   Segment       950 non-null    object
 10  Output        1000 non-null   object
dtypes: float64(2), int64(5), object(4)
memory usage: 93.8+ KB

In [ ]:
Challenge 17 – Real Company Dataset
Manager asks
Remove duplicate records

Fill missing values
Rename all business columns
Add company prefix
Display summary
Display target counts

In [13]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [14]:
df.drop_duplicates(inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median())
df["AnnualIncome"] = df["AnnualIncome"].fillna(df["AnnualIncome"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
}, inplace=True)

df.columns = "Company_" + df.columns
print(df.describe())
print(df["Company_Customer_Status"].value_counts())

       Company_Customer_ID  Company_Age  Company_Income  Company_Spending  \
count          1000.000000  1000.000000     1000.000000       1000.000000
mean          10500.500000    44.202000   112452.763000      25285.558000
std             288.819436    15.130834    51081.480963      14211.735656
min           10001.000000    18.000000    20227.000000        537.000000
25%           10250.750000    31.000000    68437.250000      13213.000000
50%           10500.500000    44.000000   112347.500000      24901.000000
75%           10750.250000    57.000000   155570.750000      37960.250000
max           11000.000000    70.000000   199967.000000      49995.000000

       Company_Credit_Score  Company_Balance  Company_Tenure
count           1000.000000      1000.000000     1000.000000
mean             603.088000     97557.565779        5.241000
std              176.605486     54430.062006        3.179155
min              300.000000       547.600000        0.000000
25%              441.000000     52074.240000        2.000000
50%              606.500000     97557.565779        5.000000
75%              758.250000    142297.910000        8.000000
max              900.000000    199885.880000       10.000000
Company_Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64

In [ ]:
Challenge 18 – Customer Summary
Generate
Mean Balance
Median Balance
Mean Age
Median AnnualIncome
Then
fill missing values using these statistics.

In [8]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [9]:
mean_balance = df["Balance"].mean()
median_balance = df["Balance"].median()
mean_age = df["Age"].mean()
median_income = df["AnnualIncome"].median()
print(mean_balance)
print(median_balance)
print(mean_age)
print(median_income)
df["Balance"] = df["Balance"].fillna(mean_balance)
df["Age"] = df["Age"].fillna(mean_age)
df["AnnualIncome"] = df["AnnualIncome"].fillna(median_income)
print(df.isnull().sum())

97523.53566563467
95100.06
44.24948453608248
112358.0
CustomerID       0
Age              0
AnnualIncome     0
Spending         0
CreditScore      0
Balance          0
Tenure           0
Geography       51
Gender          52
Segment         51
Target           0
dtype: int64

In [ ]:
Challenge 19 – Transformation Challenge
Create
Income_in_Lakhs
Balance_in_Lakhs

SeniorCitizen
HighCreditScore
where
SeniorCitizen = Age + 0
HighCreditScore = CreditScore * 1
(No conditional statements.)

In [10]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Task_dataset - Task_dataset.csv")
df.head()

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn

In [11]:
df["Income_in_Lakhs"] = df["AnnualIncome"] / 100000
df["Balance_in_Lakhs"] = df["Balance"] / 100000
df["SeniorCitizen"] = df["Age"] + 0
df["HighCreditScore"] = df["CreditScore"] * 1
df.head(10)

,CustomerID,Age,AnnualIncome,Spending,CreditScore,Balance,Tenure,Geography,Gender,Segment,Target,Income_in_Lakhs,Balance_in_Lakhs,SeniorCitizen,HighCreditScore
0,10001,58.0,49184.0,2139,581,NaN,2,France,Male,SME,Stay,0.49184,NaN,58.0,581
1,10002,65.0,162964.0,6197,732,6356.54,1,USA,Male,SME,Churn,1.62964,0.063565,65.0,732
2,10003,56.0,26956.0,37281,503,143203.92,8,Canada,Male,Corporate,Stay,0.26956,1.432039,56.0,503
3,10004,55.0,92926.0,925,463,139627.88,5,NaN,Male,Retail,Churn,0.92926,1.396279,55.0,463
4,10005,66.0,108236.0,7198,394,75985.46,5,UK,Other,Corporate,Churn,1.08236,0.759855,66.0,394
5,10006,69.0,31390.0,48323,770,107245.62,6,India,Other,Corporate,Stay,0.31390,1.072456,69.0,770
6,10007,58.0,182141.0,24200,891,38457.72,1,India,Other,Retail,Churn,1.82141,0.384577,58.0,891
7,10008,67.0,95861.0,5729,538,173296.73,6,UK,Female,SME,Stay,0.95861,1.732967,67.0,538
8,10009,41.0,62638.0,24760,663,41901.41,4,France,Other,SME,Stay,0.62638,0.419014,41.0,663
9,10010,22.0,179680.0,42113,475,106827.98,3,USA,Female,Corporate,Churn,1.79680,1.068280,22.0,475

In [ ]:
Challenge 20 – Final Interview Project
Your manager gives you a dirty customer dataset.
Prepare the final dataset.
Requirements
Load dataset
Check information
Find missing values
Remove duplicates
Rename
CustomerID
AnnualIncome
CreditScore
Target

Convert
Age

AnnualIncome
Balance

Fill missing values
Remove
Segment
CustomerID
Create new columns
TotalMoney = Balance + AnnualIncome
AgeAfter5Years = Age + 5
MonthlyIncome = AnnualIncome / 12
CreditScoreDouble = CreditScore * 2Display
• Head
• Tail
• Sample
• Describe
• Target counts
• Final information

In [12]:
df.info()
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
df.rename(columns={
    "CustomerID": "Customer_ID",
    "AnnualIncome": "Income",
    "CreditScore": "Credit_Score",
    "Target": "Customer_Status"
}, inplace=True)
df["Age"] = df["Age"].fillna(df["Age"].median()).astype(int)
df["Income"] = df["Income"].astype(float)
df["Balance"] = df["Balance"].astype(float)
df["Income"] = df["Income"].fillna(df["Income"].median())
df["Balance"] = df["Balance"].fillna(df["Balance"].mean())
df.drop(columns=["Segment", "Customer_ID"], inplace=True)
df["TotalMoney"] = df["Balance"] + df["Income"]
df["AgeAfter5Years"] = df["Age"] + 5
df["MonthlyIncome"] = df["Income"] / 12
df["CreditScoreDouble"] = df["Credit_Score"] * 2
print("First 5 Rows:")
print(df.head())
print("Last 5 Rows:")
print(df.tail())
print("Random Sample:")
print(df.sample(10))
print("Statistical Summary:")
print(df.describe())
print("Customer Status Counts:")
print(df["Customer_Status"].value_counts())
print("Final Dataset Information:")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        1020 non-null   int64
 1   Age               970 non-null    float64
 2   AnnualIncome      967 non-null    float64
 3   Spending          1020 non-null   int64
 4   CreditScore       1020 non-null   int64
 5   Balance           969 non-null    float64
 6   Tenure            1020 non-null   int64
 7   Geography         969 non-null    object
 8   Gender            968 non-null    object
 9   Segment           969 non-null    object
 10  Target            1020 non-null   object
 11  Income_in_Lakhs   967 non-null    float64
 12  Balance_in_Lakhs  969 non-null    float64
 13  SeniorCitizen     970 non-null    float64
 14  HighCreditScore   1020 non-null   int64
dtypes: float64(6), int64(5), object(4)
memory usage: 119.7+ KB
CustomerID           0
Age                 50
AnnualIncome        53
Spending             0
CreditScore          0
Balance             51
Tenure               0
Geography           51
Gender              52
Segment             51
Target               0
Income_in_Lakhs     53
Balance_in_Lakhs    51
SeniorCitizen       50
HighCreditScore      0
dtype: int64
First 5 Rows:
   Age    Income  Spending  Credit_Score        Balance  Tenure Geography  \
0   58   49184.0      2139           581   97557.565779       2    France
1   65  162964.0      6197           732    6356.540000       1       USA
2   56   26956.0     37281           503  143203.920000       8    Canada
3   55   92926.0       925           463  139627.880000       5       NaN
4   66  108236.0      7198           394   75985.460000       5        UK

  Gender Customer_Status  Income_in_Lakhs  Balance_in_Lakhs  SeniorCitizen  \
0   Male            Stay          0.49184               NaN           58.0
1   Male           Churn          1.62964          0.063565           65.0
2   Male            Stay          0.26956          1.432039           56.0
3   Male           Churn          0.92926          1.396279           55.0
4  Other           Churn          1.08236          0.759855           66.0

   HighCreditScore     TotalMoney  AgeAfter5Years  MonthlyIncome  \
0              581  146741.565779              63    4098.666667
1              732  169320.540000              70   13580.333333
2              503  170159.920000              61    2246.333333
3              463  232553.880000              60    7743.833333
4              394  184221.460000              71    9019.666667

   CreditScoreDouble
0               1162
1               1464
2               1006
3                926
4                788
Last 5 Rows:
     Age    Income  Spending  Credit_Score    Balance  Tenure Geography  \
995   34   81731.0     40980           761  181465.65       5   Germany
996   47   42475.0      1176           780   26640.99       5    France
997   31  120531.0     46929           733  147220.82       4     India
998   21   33661.0     22314           540   94186.48       5       NaN
999   63   31930.0       851           559  100908.40       6        UK

     Gender Customer_Status  Income_in_Lakhs  Balance_in_Lakhs  SeniorCitizen  \
995   Other            Stay          0.81731          1.814656           34.0
996  Female            Stay          0.42475          0.266410           47.0
997    Male            Stay          1.20531          1.472208           31.0
998   Other            Stay          0.33661          0.941865           21.0
999  Female            Stay          0.31930          1.009084           63.0

     HighCreditScore  TotalMoney  AgeAfter5Years  MonthlyIncome  \
995              761   263196.65              39    6810.916667
996              780    69115.99              52    3539.583333
997              733   267751.82              36   10044.250000
998              540   127847.48              26    2805.083333
999              559   132838.40              68    2660.833333

     CreditScoreDouble
995               1522
996               1560
997               1466
998               1080
999               1118
Random Sample:
     Age    Income  Spending  Credit_Score    Balance  Tenure Geography  \
832   62   68303.0     17102           601   93391.12       1    France
78    66  119385.0     18735           731   50454.31       1    Canada
947   52   24632.0      2570           740  176025.13       1       NaN
489   32   86162.0     40368           612  142548.10      10        UK
112   46   92917.0     12394           899   87177.00       7     India
610   45   80158.0     32096           690   70103.56       9     India
145   25  139219.0     24655           568  116912.02      10        UK
777   37  105809.0      9890           400  164427.70       8    France
19    67  159029.0       537           631   97721.14       1        UK
94    53  106714.0     23556           764   54183.29       4       USA

     Gender Customer_Status  Income_in_Lakhs  Balance_in_Lakhs  SeniorCitizen  \
832  Female           Churn          0.68303          0.933911           62.0
78     Male           Churn          1.19385          0.504543           66.0
947  Female           Churn          0.24632          1.760251           52.0
489  Female            Stay          0.86162          1.425481           32.0
112  Female            Stay          0.92917          0.871770           46.0
610  Female            Stay          0.80158          0.701036           45.0
145    Male            Stay          1.39219          1.169120           25.0
777    Male           Churn          1.05809          1.644277           37.0
19   Female           Churn          1.59029          0.977211           67.0
94     Male            Stay          1.06714          0.541833           53.0

     HighCreditScore  TotalMoney  AgeAfter5Years  MonthlyIncome  \
832              601   161694.12              67    5691.916667
78               731   169839.31              71    9948.750000
947              740   200657.13              57    2052.666667
489              612   228710.10              37    7180.166667
112              899   180094.00              51    7743.083333
610              690   150261.56              50    6679.833333
145              568   256131.02              30   11601.583333
777              400   270236.70              42    8817.416667
19               631   256750.14              72   13252.416667
94               764   160897.29              58    8892.833333

     CreditScoreDouble
832               1202
78                1462
947               1480
489               1224
112               1798
610               1380
145               1136
777                800
19                1262
94                1528
Statistical Summary:
               Age         Income      Spending  Credit_Score        Balance  \
count  1000.000000    1000.000000   1000.000000   1000.000000    1000.000000
mean     44.202000  112452.763000  25285.558000    603.088000   97557.565779
std      15.130834   51081.480963  14211.735656    176.605486   54430.062006
min      18.000000   20227.000000    537.000000    300.000000     547.600000
25%      31.000000   68437.250000  13213.000000    441.000000   52074.240000
50%      44.000000  112347.500000  24901.000000    606.500000   97557.565779
75%      57.000000  155570.750000  37960.250000    758.250000  142297.910000
max      70.000000  199967.000000  49995.000000    900.000000  199885.880000

            Tenure  Income_in_Lakhs  Balance_in_Lakhs  SeniorCitizen  \
count  1000.000000       950.000000        950.000000     950.000000
mean      5.241000         1.124583          0.975576      44.212632
std       3.179155         0.524099          0.558455      15.524244
min       0.000000         0.202270          0.005476      18.000000
25%       2.000000         0.659225          0.500039      30.000000
50%       5.000000         1.123475          0.951746      44.000000
75%       8.000000         1.579730          1.441981      58.000000
max      10.000000         1.999670          1.998859      70.000000

       HighCreditScore     TotalMoney  AgeAfter5Years  MonthlyIncome  \
count      1000.000000    1000.000000     1000.000000    1000.000000
mean        603.088000  210010.328779       49.202000    9371.063583
std         176.605486   73150.769298       15.130834    4256.790080
min         300.000000   33432.390000       23.000000    1685.583333
25%         441.000000  156611.867500       36.000000    5703.104167
50%         606.500000  209916.897889       49.000000    9362.291667
75%         758.250000  263542.793945       62.000000   12964.229167
max         900.000000  390628.400000       75.000000   16663.916667

       CreditScoreDouble
count        1000.000000
mean         1206.176000
std           353.210972
min           600.000000
25%           882.000000
50%          1213.000000
75%          1516.500000
max          1800.000000
Customer Status Counts:
Customer_Status
Churn    506
Stay     494
Name: count, dtype: int64
Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                1000 non-null   int64
 1   Income             1000 non-null   float64
 2   Spending           1000 non-null   int64
 3   Credit_Score       1000 non-null   int64
 4   Balance            1000 non-null   float64
 5   Tenure             1000 non-null   int64
 6   Geography          950 non-null    object
 7   Gender             950 non-null    object
 8   Customer_Status    1000 non-null   object
 9   Income_in_Lakhs    950 non-null    float64
 10  Balance_in_Lakhs   950 non-null    float64
 11  SeniorCitizen      950 non-null    float64
 12  HighCreditScore    1000 non-null   int64
 13  TotalMoney         1000 non-null   float64
 14  AgeAfter5Years     1000 non-null   int64
 15  MonthlyIncome      1000 non-null   float64
 16  CreditScoreDouble  1000 non-null   int64
dtypes: float64(7), int64(7), object(3)
memory usage: 140.6+ KB