In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:

df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [9]:
df.head(8)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1

In [ ]:
3. Display the last 12 rows of the dataset.

In [10]:
df.tail(12)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9988,9989,15589329,Pirozzi,775,France,Male,30,4,0.00,2,1,0,49337.84,0
9989,9990,15605622,McMillan,841,Spain,Male,28,4,0.00,2,1,1,179436.60,0
9990,9991,15798964,Nkemakonam,714,Germany,Male,33,3,35016.60,1,1,0,53667.08,0
9991,9992,15769959,Ajuluchukwu,597,France,Female,53,4,88381.21,1,1,0,69384.71,1
9992,9993,15657105,Chukwualuka,726,Spain,Male,36,2,0.00,1,1,0,195192.40,0
9993,9994,15569266,Rahman,644,France,Male,28,7,155060.41,1,1,0,29179.52,0
9994,9995,15719294,Wood,800,France,Female,29,2,0.00,2,0,0,167773.55,0
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
4. Show 10 random rows from the dataset.

In [12]:
df.sample(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
5445,5446,15779174,Young,451,France,Female,36,2,0.00,2,1,1,180142.42,0
9559,9560,15761706,Y?an,705,Spain,Female,39,8,144102.32,1,1,1,11682.36,0
6060,6061,15669253,Gibson,754,Spain,Male,39,7,157691.98,2,1,0,133600.89,1
6355,6356,15570414,Chizoba,618,Spain,Male,41,4,115251.64,1,0,0,136435.75,0
3772,3773,15699486,Johnson,745,Spain,Male,34,7,132944.53,1,1,1,31802.92,0
7710,7711,15754168,McIntosh,506,France,Female,40,3,0.00,1,1,1,144345.58,0
1344,1345,15691104,Kennedy,460,Germany,Female,40,6,119507.58,2,1,0,91560.63,1
5248,5249,15700366,Burton,669,France,Male,39,3,119452.03,1,1,1,171575.54,0
9601,9602,15797692,Volkova,659,France,Female,33,7,89939.62,1,1,0,136540.09,0
177,178,15790355,Okechukwu,606,Germany,Male,36,5,190479.48,2,0,0,179351.89,0

In [ ]:
5. Find the shape of the dataset.
 How many rows are there?
 How many columns are there?

In [27]:
print(df.shape)
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

(10000, 14)
Rows: 10000
Columns: 14

In [ ]:
6. Display complete information about the dataset using one method.
o Number of non-null values
o Data types
o Memory usage

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [ ]:
7. Print the names of all columns in the dataset.

In [18]:
print(df.columns)

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
8. Find the data type of every column.

In [19]:
print(df.dtypes)

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [20]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [21]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
10.Select only one column:
o CreditScore

In [22]:
df["CreditScore"]

0       619
1       608
2       502
3       699
4       850
       ...
9995    771
9996    516
9997    709
9998    772
9999    792
Name: CreditScore, Length: 10000, dtype: int64

In [ ]:
11.Select the following multiple columns:
o CustomerId
o Surname
o Balance
o Exited

In [8]:
df[["CustomerId", "Surname", "Balance", "Exited"]]

      CustomerId    Surname    Balance  Exited
0       15634602   Hargrave       0.00       1
1       15647311       Hill   83807.86       0
2       15619304       Onio  159660.80       1
3       15701354       Boni       0.00       0
4       15737888   Mitchell  125510.82       0
...          ...        ...        ...     ...
9995    15606229   Obijiaku       0.00       0
9996    15569892  Johnstone   57369.61       0
9997    15584532        Liu       0.00       1
9998    15682355  Sabbatini   75075.31       1
9999    15628319     Walker  130142.79       0

[10000 rows x 4 columns]

In [ ]:
12.Display only numeric columns using select_dtypes().

In [23]:
df.select_dtypes(include=['number'])

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,771,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,516,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,709,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,772,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,792,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
13.Generate the statistical summary of all numeric columns using describe().

In [24]:
df.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
14.Check for duplicate rows in the dataset.
o How many duplicate rows exist?

o Remove all duplicate rows.

In [25]:
print(df.duplicated().sum())   
df = df.drop_duplicates()

0

In [ ]:
15.Count the number of customers in each class of the Exited column using
value_counts().

In [6]:
import pandas as pd
df = pd.read_csv("C:\\Users\\LENOVO\\Downloads\\Bank_customer_churn - Bank_customer_churn.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df["Exited"].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

#Operators + Loops

1. Take two numbers from user. Perform all arithmetic operations and also check
which number is greater using comparison operators.

In [3]:
a=5
b=6
c=a+b
d=a-b
e=a*b
f=a//b
g=a%b
h=a/b
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(a>b)

11
-1
30
0
5
0.8333333333333334
False

2. Print all numbers from 1 to 50. Skip multiples of 5 using continue and stop
completely when number 40 is reached using break.

In [4]:
for i in range(1, 51):
    if i == 40:
        break
    if i % 5 == 0:
        continue
    print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39

3. Take numbers from user until they enter negative number. Calculate sum and
average using while loop.

In [1]:
sum = 0
count = 0
while True:
    n=int(input())
    if n < 0:
        break
    sum = sum + n
    count += 1
if count > 0:
    avg = sum / count
    print("sum:",sum)
    print("avg:",avg)

 12
 34
 78
 -10

sum: 124
avg: 41.333333333333336

In [ ]:
4. Print the following pattern using nested loops:
*****
****
***
**
*

In [2]:
n=5
for i in range(1,n+1):
    for j in range(n - i + 1):
        print("*", end =" ")
    print()

* * * * *
* * * *
* * *
* *
*

In [ ]:
5. Find the factorial of a number using for loop and also using while loop.

In [3]:
n = int(input())
fact = 1
for i in range(1, n + 1):
    fact = fact * i
print(fact)

 5

120

In [4]:
num = int(input())
fact = 1
i = 1
while i <= num:
    fact = fact * i
    i = i + 1
print(fact)

 5

120

In [ ]:
6. Take a string and perform: convert to uppercase, count occurrences of ‘a’, replace
spaces with -, and check if it starts with “Hello”.

In [5]:
text = "My name is me and i love me. me,my life,my rulezz"
print(text.upper())
print(text.count("a"))
print(text.replace(" ", "-"))
print(text.startswith("Hello"))

MY NAME IS ME AND I LOVE ME. ME,MY LIFE,MY RULEZZ
2
My-name-is-me-and-i-love-me.-me,my-life,my-rulezz
False

In [ ]:
7. Create a list of 6 numbers. Use append, insert, remove, pop, sort (descending)
and reverse.

In [6]:
n = [1,2,3,4,5,6]
print(n)
n.append(40)
print(n)
n.insert(2, 50)
print(n)
n.remove(5)
print(n)
n.pop()
print(n)
n.sort(reverse=True)
print(n)
n.reverse()
print(n)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 40]
[1, 2, 50, 3, 4, 5, 6, 40]
[1, 2, 50, 3, 4, 6, 40]
[1, 2, 50, 3, 4, 6]
[50, 6, 4, 3, 2, 1]
[1, 2, 3, 4, 6, 50]

In [ ]:
8. Create a dictionary of 4 students (name:marks). Print only those students who
scored more than 80 using items().

In [8]:
students = {
    "Aksh": 85,
    "varsh": 70,
    "hari": 90,
    "aksh2": 75
}
for i, j in students.items():
    if j > 80:
        print(i, j)

Aksh 85
hari 90

9. Create two sets and perform union, intersection, difference. Also add and discard
elements.

In [9]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))
set1.add(7)
print(set1)
set1.discard(2)
print(set1)

{1, 2, 3, 4, 5, 6}
{3, 4}
{1, 2}
{1, 2, 3, 4, 7}
{1, 3, 4, 7}

#OOP + Encapsulation

10. Create a class Student with private attribute __marks. Add getter and setter with
validation

In [10]:
class Student:
    def __init__(self):
        self.__marks = 0
    def set_marks(self, marks):
        if marks >= 0 and marks <= 100:
            self.__marks = marks
        else:
            print("Invalid Marks")
    def get_marks(self):
        return self.__marks
s = Student()
s.set_marks(85)
print(s.get_marks())

85

11. Create class BankAccount with private __balance. Add deposit and withdraw
methods. Raise custom exception if balance becomes negative.

In [11]:
class NegativeBalanceError(Exception):
    pass
class BankAccount:
    def __init__(self):
        self.__balance = 0
    def deposit(self, amount):
        self.__balance = self.__balance + amount
        print("Balance:", self.__balance)
    def withdraw(self, amount):
        if self.__balance - amount < 0:
            raise NegativeBalanceError("Insufficient Balance")
        self.__balance = self.__balance - amount
        print("Balance:", self.__balance)
b = BankAccount()
b.deposit(1000)
try:
    b.withdraw(1200)
except NegativeBalanceError as e:
    print(e)

Balance: 1000
Insufficient Balance

In [13]:
class Employee:
    company_name = "ABC Company"  
    def __init__(self, name):
        self.name = name
e1 = Employee("akshitha")
e2 = Employee("kams")
print(e1.name, e1.company_name)
print(e2.name, e2.company_name)
Employee.company_name = "XYZ Company"
print(e1.name, e1.company_name)
print(e2.name, e2.company_name)

akshitha ABC Company
kams ABC Company
akshitha XYZ Company
kams XYZ Company

13. Create class Product with private __price. Add getter and setter. Setter should
not allow price less than 100.

In [14]:
class Product:
    def __init__(self):
        self.__price = 0
    def set_price(self, price):
        if price >= 100:
            self.__price = price
        else:
            print("Price should be 100 or more")
    def get_price(self):
        return self.__price
p = Product()
p.set_price(500)
print(p.get_price())
p.set_price(50)

500
Price should be 100 or more

14. Create class Rectangle with private length and width. Add method to calculate
area and perimeter.

In [15]:
class Rectangle:
    def __init__(self, length, width):
        self.__length = length
        self.__width = width
    def area(self):
        return self.__length * self.__width
    def perimeter(self):
        return 2 * (self.__length + self.__width)
r = Rectangle(10, 5)
print(r.area())
print(r.perimeter())

50
30

#Inheritance + Abstraction + super()

15. Create single level inheritance: Person → Student. Use super() in constructor.

In [16]:
class Person:
    def __init__(self, name):
        self.name = name
class Student(Person):
    def __init__(self, name, roll_no):
        super().__init__(name)
        self.roll_no = roll_no
s = Student("akshi", 101)
print("Name:", s.name)
print("Roll No:", s.roll_no)

Name: akshi
Roll No: 101

16. Create multi-level inheritance: Person → Employee → Manager. Override a
method at each level.

In [17]:
class Person:
    def show(self):
        print("person")
class Employee(Person):
    def show(self):
        print("Employee")
class Manager(Employee):
    def show(self):
        print("Manager")
m = Manager()
m.show()

Manager

17. Create hierarchical inheritance: Parent Animal → Dog and Cat. Override sound()
method.

In [18]:
class Animal:
    def sound(self):
        print("Animal makes a sound")
class Dog(Animal):
    def sound(self):
        print("Dog barks")
class Cat(Animal):
    def sound(self):
        print("Cat meows")
d = Dog()
c = Cat()
d.sound()
c.sound()

Dog barks
Cat meows

18. Create abstract class Shape with abstract method area(). Implement it in Circle
and Square using super().

In [19]:
from abc import ABC, abstractmethod
class Shape(ABC):
    @abstractmethod
    def area(self):
        pass
class Circle(Shape):
    def __init__(self, radius):
        super().__init__()
        self.radius = radius
    def area(self):
        return 3.14 * self.radius * self.radius
class Square(Shape):
    def __init__(self, side):
        super().__init__()
        self.side = side
    def area(self):
        return self.side * self.side
c = Circle(5)
s = Square(4)
print(c.area())
print(s.area())

78.5
16

In [ ]:
19. Create multiple inheritance with two classes Father and Mother. Create child
class and resolve method conflict.

In [20]:
class Father:
    def show(self):
        print("Father")
class Mother:
    def show(self):
        print("Mother")
class Child(Father, Mother):
    def show(self):
        print("Child")
c = Child()
c.show()

Child

#Overloading + Exception + File Handling

In [21]:
class Student:
    def __init__(self, *marks):
        self.marks = marks
    def __add__(self, other):
        return sum(self.marks) + sum(other.marks)
s1 = Student(80, 90)
s2 = Student(70, 60)
print(s1 + s2)

170

In [ ]:
21. Create class Point and overload + and > operators.

In [22]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __add__(self, other):
        return Point(self.x + other.x, self.y + other.y)
    def __gt__(self, other):
        return (self.x + self.y) > (other.x + other.y)
p1 = Point(2, 3)
p2 = Point(4, 5)
p3 = p1 + p2
print(p3.x, p3.y)
print("p1 > p2:", p1 > p2)

6 8
p1 > p2: False

In [ ]:
22. Write a program that handles ZeroDivisionError, ValueError and IndexError using
multiple except blocks.

In [23]:
try:
    a = int(input("Enter a number: "))
    b = int(input("Enter another number: "))
    print("Division:", a / b)
    numbers = [10, 20, 30]
    index = int(input("Enter index: "))
    print("Element:", numbers[index])
except ZeroDivisionError:
    print("Cannot divide by zero")
except ValueError:
    print("Please enter only numbers")
except IndexError:
    print("Invalid index")

Enter a number:  24
Enter another number:  56

Division: 0.42857142857142855

Enter index:  1

Element: 20

In [ ]:
23. Create a custom exception InvalidAgeError. Raise it if age is less than 18.

In [24]:
class InvalidAgeError(Exception):
    pass
age = int(input("Enter your age: "))
try:
    if age < 18:
        raise InvalidAgeError("Age must be 18 or above")
    else:
        print("Eligible")
except InvalidAgeError as e:
    print(e)

Enter your age:  12

Age must be 18 or above

In [ ]:
24. Write a program to read a file, count number of words, and write the count into
another file.

In [25]:
file = open("data.txt", "r")
text = file.read()
file.close()
count = len(text.split())
file = open("count.txt", "w")
file.write("Number of words: " + str(count))
file.close()
print("Word count written successfully")

Word count written successfully

In [ ]:
25. Create a menu-driven program for file operations: Write, Read, Append, and Exit.
Handle FileNotFoundError.

In [26]:
while True:
    print("\n1. Write")
    print("2. Read")
    print("3. Append")
    print("4. Exit")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        file = open("data.txt", "w")
        text = input("Enter text: ")
        file.write(text)
        file.close()
        print("Written successfully")
    elif choice == 2:
        try:
            file = open("data.txt", "r")
            print(file.read())
            file.close()
        except FileNotFoundError:
            print("File not found")
    elif choice == 3:
        file = open("data.txt", "a")
        text = input("Enter text to add: ")
        file.write("\n" + text)
        file.close()
        print("Added successfully")
    elif choice == 4:
        print("Exit")
        break
    else:
        print("Invalid choice")

1. Write
2. Read
3. Append
4. Exit

Enter your choice:  3
Enter text to add:  2

Added successfully

1. Write
2. Read
3. Append
4. Exit

Enter your choice:  5

Invalid choice

1. Write
2. Read
3. Append
4. Exit

Enter your choice:  4

Exit

26. Create a class Student with private marks list.
• Setter should validate each mark (0-100)
• Overload > operator to compare two students based on average
• Raise custom exception if marks list is empty

In [28]:
class EmptyMarksError(Exception):
    pass
class Student:
    def __init__(self):
        self.__marks = []
    def set_marks(self, marks):
        if len(marks) == 0:
            raise EmptyMarksError("Marks list is empty")
        for mark in marks:
            if mark < 0 or mark > 100:
                print("Invalid mark:", mark)
                return
        self.__marks = marks
    def average(self):
        total = 0
        for mark in self.__marks:
            total = total + mark
        return total / len(self.__marks)
    def __gt__(self, other):
        return self.average() > other.average()
s1 = Student()
s2 = Student()
try:
    s1.set_marks([80, 90, 70])
    s2.set_marks([60, 75, 85])
    print("Student 1 Average:", s1.average())
    print("Student 2 Average:", s2.average())
    if s1 > s2:
        print("Student 1 has higher average")
    else:
        print("Student 2 has higher average")
except EmptyMarksError as e:
    print(e)

Student 1 Average: 80.0
Student 2 Average: 73.33333333333333
Student 1 has higher average